language: php

php:
  - '7.1'
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm

before_script:
  - composer install

script:
  - vendor/bin/phpmd src/ text phpmd.xml
  - vendor/bin/phpcs --standard=phpcs.xml
